import { auth, db } from './firebase-config.js';
import {
  createUserWithEmailAndPassword,
    signInWithEmailAndPassword,
      onAuthStateChanged,
        signOut
        } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js";
        import {
          doc, getDoc, setDoc, collection, query, where, getDocs
          } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js";

          const splash = document.getElementById('splash');
          const appDiv = document.getElementById('app');
          const loginScreen = document.getElementById('login-screen');
          const loginError = document.getElementById('login-error');
          const userInfo = document.getElementById('user-info');
          const mainContent = document.getElementById('main-content');
          const navBtns = document.querySelectorAll('.nav-btn');

          let currentUser = null;

          onAuthStateChanged(auth, async (user) => {
            if (user) {
                currentUser = await loadUserProfile(user);
                    showApp();
                      } else {
                          showLogin();
                            }
                            });

                            function showApp() {
                              splash.classList.add('hidden');
                                loginScreen.classList.add('hidden');
                                  appDiv.classList.remove('hidden');
                                    userInfo.textContent = currentUser?.username || '';
                                      navigateTo('inicio');
                                      }

                                      function showLogin() {
                                        splash.classList.add('hidden');
                                          appDiv.classList.add('hidden');
                                            loginScreen.classList.remove('hidden');
                                            }

                                            document.querySelectorAll('.auth-tab').forEach(tab => {
                                              tab.addEventListener('click', () => {
                                                  document.querySelectorAll('.auth-tab').forEach(t => t.classList.remove('active'));
                                                      tab.classList.add('active');
                                                          const target = tab.dataset.tab;
                                                              document.getElementById('tab-login').classList.toggle('hidden', target !== 'login');
                                                                  document.getElementById('tab-register').classList.toggle('hidden', target !== 'register');
                                                                      hideError();
                                                                        });
                                                                        });

                                                                        document.getElementById('login-btn').addEventListener('click', async () => {
                                                                          const username = document.getElementById('login-username').value.trim().toLowerCase();
                                                                            const password = document.getElementById('login-password').value;
                                                                              if (!username || !password) return showError('Completa todos los campos');
                                                                                const btn = document.getElementById('login-btn');
                                                                                  btn.disabled = true;
                                                                                    btn.textContent = 'Entrando...';
                                                                                      hideError();
                                                                                        try {
                                                                                            const email = `${username}@estiria.app`;
                                                                                                await signInWithEmailAndPassword(auth, email, password);
                                                                                                  } catch (err) {
                                                                                                      showError('Usuario o contraseña incorrectos');
                                                                                                          btn.disabled = false;
                                                                                                              btn.textContent = 'Entrar a Estiria';
                                                                                                                }importimport
                                                                                                                });
                                                                                                                document.getElementById('register-btn').addEventListener('click', async () => {
                                                                                                                      const username = document.getElementById('reg-username').value.trim().toLowerCase();
                                                                                                                        const password = document.getElementById('reg-password').value;
                                                                                                                          const password2 = document.getElementById('reg-password2').value;
                                                                                                                            const whatsapp = document.getElementById('reg-whatsapp').value.trim();

                                                                                                                              if (!username || !password) return showError('Usuario y contraseña son obligatorios');
                                                                                                                                if (username.length < 3) return showError('El usuario debe tener al menos 3 caracteres');
                                                                                                                                  if (password.length < 6) return showError('La contraseña debe tener al menos 6 caracteres');
                                                                                                                                    if (password !== password2) return showError('Las contraseñas no coinciden');
                                                                                                                                      if (!/^[a-z0-9_]+$/.test(username)) return showError('Solo letras, números y guión bajo');

                                                                                                                                        const btn = document.getElementById('register-btn');
                                                                                                                                          btn.disabled = true;
                                                                                                                                            btn.textContent = 'Creando cuenta...';
                                                                                                                                              hideError();

                                                                                                                                                try {
                                                                                                                                                    const q = query(collection(db, 'usuarios'), where('username', '==', username));
                                                                                                                                                        const snap = await getDocs(q);
                                                                                                                                                            if (!snap.empty) {
                                                                                                                                                                  showError('Ese nombre de usuario ya está ocupado');
                                                                                                                                                                        btn.disabled = false;
                                                                                                                                                                              btn.textContent = 'Crear cuenta';
                                                                                                                                                                                    return;
                                                                                                                                                                                        }
                                                                                                                                                                                            const email = `${username}@estiria.app`;
                                                                                                                                                                                                const cred = await createUserWithEmailAndPassword(auth, email, password);
                                                                                                                                                                                                    await setDoc(doc(db, 'usuarios', cred.user.uid), {
                                                                                                                                                                                                          uid: cred.user.uid,
                                                                                                                                                                                                                username,
                                                                                                                                                                                                                      whatsapp: whatsapp || '',
                                                                                                                                                                                                                            rol: 'jugador',
                                                                                                                                                                                                                                  creadoEn: new Date().toISOString(),
                                                                                                                                                                                                                                        saldo: 0
                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                              } catch (err) {
                                                                                                                                                                                                                                                  showError('Error al crear cuenta: ' + err.message);
                                                                                                                                                                                                                                                      btn.disabled = false;
                                                                                                                                                                                                                                                          btn.textContent = 'Crear cuenta';
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                            async function loadUserProfile(user) {
                                                                                                                                                                                                                                                              const ref = doc(db, 'usuarios', user.uid);
                                                                                                                                                                                                                                                                const snap = await getDoc(ref);
                                                                                                                                                                                                                                                                  if (snap.exists()) return snap.data();
                                                                                                                                                                                                                                                                    return { uid: user.uid, username: user.email?.split('@')[0], rol: 'jugador' };
                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                    navBtns.forEach(btn => {
                                                                                                                                                                                                                                                                      btn.addEventListener('click', () => {
                                                                                                                                                                                                                                                                          navBtns.forEach(b => b.classList.remove('active'));
                                                                                                                                                                                                                                                                              btn.classList.add('active');
                                                                                                                                                                                                                                                                                  navigateTo(btn.dataset.section);
                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                    function navigateTo(section) {
                                                                                                                                                                                                                                                                                      document.getElementById('header-title').textContent =
                                                                                                                                                                                                                                                                                          section.charAt(0).toUpperCase() + section.slice(1);
                                                                                                                                                                                                                                                                                            switch (section) {
                                                                                                                                                                                                                                                                                                case 'inicio':     renderInicio(); break;
                                                                                                                                                                                                                                                                                                    case 'banco':      renderBanco(); break;
                                                                                                                                                                                                                                                                                                        case 'biblioteca': renderBiblioteca(); break;
                                                                                                                                                                                                                                                                                                            case 'perfil':     renderPerfil(); break;
                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                              function renderInicio() {
                                                                                                                                                                                                                                                                                                                mainContent.innerHTML = `
                                                                                                                                                                                                                                                                                                                    <div class="welcome-banner">
                                                                                                                                                                                                                                                                                                                          <h2>⚔️ Bienvenido a Estiria</h2>
                                                                                                                                                                                                                                                                                                                                <p>${currentUser?.username || 'Ciudadano'}</p>
                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                        <div class="card">
                                                                                                                                                                                                                                                                                                                                              <h3>📢 Anuncios</h3>
                                                                                                                                                                                                                                                                                                                                                    <p>Próximamente...</p>
                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                            <div class="card">
                                                                                                                                                                                                                                                                                                                                                                  <h3>📅 Eventos</h3>
                                                                                                                                                                                                                                                                                                                                                                        <p>Próximamente...</p>
                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                ${currentUser?.rol === 'admin' ? `
                                                                                                                                                                                                                                                                                                                                                                                    <div class="card" style="border-color: var(--accent)">
                                                                                                                                                                                                                                                                                                                                                                                          <h3>🛡️ Panel Admin</h3>
                                                                                                                                                                                                                                                                                                                                                                                                <p>Tienes acceso de administrador.</p>
                                                                                                                                                                                                                                                                                                                                                                                                    </div>` : ''}
                                                                                                                                                                                                                                                                                                                                                                                                      `;
                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                      function renderBanco() {
                                                                                                                                                                                                                                                                                                                                                                                                        mainContent.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                            <div class="card">
                                                                                                                                                                                                                                                                                                                                                                                                                  <h3>🏦 Banco de Estiria</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                        <p>Próximamente...</p>
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                              `;
                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                              function renderBiblioteca() {
                                                                                                                                                                                                                                                                                                                                                                                                                                mainContent.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="card">
                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3>📚 Biblioteca</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>Próximamente...</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                      function renderPerfil() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        mainContent.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3>👤 Mi Perfil</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p><strong>Usuario:</strong> ${currentUser?.username || ''}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p><strong>Rol:</strong> ${currentUser?.rol || 'jugador'}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p><strong>WhatsApp:</strong> ${currentUser?.whatsapp || 'No registrado'}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button class="btn btn-secondary btn-full" id="logout-btn">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Cerrar sesión
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          document.getElementById('logout-btn').addEventListener('click', () => signOut(auth));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          function showError(msg) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            loginError.textContent = msg;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              loginError.classList.remove('hidden');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              function hideError() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                loginError.classList.add('hidden');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }