import { auth, db } from './firebase-config.js';
import {
  RecaptchaVerifier,
    signInWithPhoneNumber,
      onAuthStateChanged
      } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js";
      import {
        doc, getDoc, setDoc
        } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js";

        // ===== ELEMENTOS DEL DOM =====
        const splash = document.getElementById('splash');
        const app = document.getElementById('app');
        const loginScreen = document.getElementById('login-screen');
        const stepPhone = document.getElementById('step-phone');
        const stepCode = document.getElementById('step-code');
        const phoneInput = document.getElementById('phone-input');
        const codeInput = document.getElementById('code-input');
        const sendCodeBtn = document.getElementById('send-code-btn');
        const verifyCodeBtn = document.getElementById('verify-code-btn');
        const backBtn = document.getElementById('back-btn');
        const loginError = document.getElementById('login-error');
        const userInfo = document.getElementById('user-info');
        const mainContent = document.getElementById('main-content');
        const navBtns = document.querySelectorAll('.nav-btn');

        let confirmationResult = null;
        let currentUser = null;
        let currentSection = 'inicio';

        // ===== INICIALIZACIÓN =====
        onAuthStateChanged(auth, async (user) => {
          if (user) {
              currentUser = await loadUserProfile(user);
                  showApp();
                    } else {
                        showLogin();
                          }
                          });

                          // ===== MOSTRAR / OCULTAR PANTALLAS =====
                          function showApp() {
                            splash.classList.add('hidden');
                              loginScreen.classList.add('hidden');
                                app.classList.remove('hidden');
                                  userInfo.textContent = currentUser?.nombre || currentUser?.telefono || '';
                                    navigateTo('inicio');
                                    }

                                    function showLogin() {
                                      splash.classList.add('hidden');
                                        app.classList.add('hidden');
                                          loginScreen.classList.remove('hidden');
                                          }

                                          // ===== LOGIN CON TELÉFONO =====
                                          sendCodeBtn.addEventListener('click', async () => {
                                            const phone = phoneInput.value.trim();
                                              if (!phone) return showError('Ingresa tu número de WhatsApp');

                                                sendCodeBtn.disabled = true;
                                                  sendCodeBtn.textContent = 'Enviando...';
                                                    hideError();

                                                      try {
                                                          if (!window.recaptchaVerifier) {
                                                                window.recaptchaVerifier = new RecaptchaVerifier(
                                                                        auth,
                                                                                'recaptcha-container',
                                                                                        { size: 'invisible' }
                                                                                              );
                                                                                                  }
                                                                                                      confirmationResult = await signInWithPhoneNumber(
                                                                                                            auth, phone, window.recaptchaVerifier
                                                                                                                );
                                                                                                                    stepPhone.classList.add('hidden');
                                                                                                                        stepCode.classList.remove('hidden');
                                                                                                                          } catch (err) {
                                                                                                                              showError('Error al enviar código: ' + err.message);
                                                                                                                                  sendCodeBtn.disabled = false;
                                                                                                                                      sendCodeBtn.textContent = 'Enviar código';
                                                                                                                                        }
                                                                                                                                        });

                                                                                                                                        verifyCodeBtn.addEventListener('click', async () => {
                                                                                                                                          const code = codeInput.value.trim();
                                                                                                                                            if (!code) return showError('Ingresa el código');

                                                                                                                                              verifyCodeBtn.disabled = true;
                                                                                                                                                verifyCodeBtn.textContent = 'Verificando...';
                                                                                                                                                  hideError();

                                                                                                                                                    try {
                                                                                                                                                        await confirmationResult.confirm(code);
                                                                                                                                                            // onAuthStateChanged se dispara automáticamente
                                                                                                                                                              } catch (err) {
                                                                                                                                                                  showError('Código incorrecto. Intenta de nuevo.');
                                                                                                                                                                      verifyCodeBtn.disabled = false;
                                                                                                                                                                          verifyCodeBtn.textContent = 'Verificar';
                                                                                                                                                                            }
                                                                                                                                                                            });

                                                                                                                                                                            backBtn.addEventListener('click', () => {
                                                                                                                                                                              stepCode.classList.add('hidden');
                                                                                                                                                                                stepPhone.classList.remove('hidden');
                                                                                                                                                                                  sendCodeBtn.disabled = false;
                                                                                                                                                                                    sendCodeBtn.textContent = 'Enviar código';
                                                                                                                                                                                      hideError();
                                                                                                                                                                                      });

                                                                                                                                                                                      // ===== PERFIL DE USUARIO EN FIRESTORE =====
                                                                                                                                                                                      async function loadUserProfile(user) {
                                                                                                                                                                                        const ref = doc(db, 'usuarios', user.uid);
                                                                                                                                                                                          const snap = await getDoc(ref);

                                                                                                                                                                                            if (!snap.exists()) {
                                                                                                                                                                                                // Primera vez — crear perfil
                                                                                                                                                                                                    const perfil = {
                                                                                                                                                                                                          uid: user.uid,
                                                                                                                                                                                                                telefono: user.phoneNumber,
                                                                                                                                                                                                                      rol: 'jugador',
                                                                                                                                                                                                                            creadoEn: new Date().toISOString(),
                                                                                                                                                                                                                                  nombre: ''
                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                          await setDoc(ref, perfil);
                                                                                                                                                                                                                                              return perfil;
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                  return snap.data();
                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                  // ===== NAVEGACIÓN =====
                                                                                                                                                                                                                                                  navBtns.forEach(btn => {
                                                                                                                                                                                                                                                    btn.addEventListener('click', () => {
                                                                                                                                                                                                                                                        navBtns.forEach(b => b.classList.remove('active'));
                                                                                                                                                                                                                                                            btn.classList.add('active');
                                                                                                                                                                                                                                                                navigateTo(btn.dataset.section);
                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                  function navigateTo(section) {
                                                                                                                                                                                                                                                                    currentSection = section;
                                                                                                                                                                                                                                                                      document.getElementById('header-title').textContent =
                                                                                                                                                                                                                                                                          section.charAt(0).toUpperCase() + section.slice(1);

                                                                                                                                                                                                                                                                            switch (section) {
                                                                                                                                                                                                                                                                                case 'inicio':    renderInicio(); break;
                                                                                                                                                                                                                                                                                    case 'banco':     renderBanco(); break;
                                                                                                                                                                                                                                                                                        case 'biblioteca': renderBiblioteca(); break;
                                                                                                                                                                                                                                                                                            case 'perfil':    renderPerfil(); break;
                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                              // ===== SECCIONES =====
                                                                                                                                                                                                                                                                                              function renderInicio() {
                                                                                                                                                                                                                                                                                                mainContent.innerHTML = `
                                                                                                                                                                                                                                                                                                    <div class="welcome-banner">
                                                                                                                                                                                                                                                                                                          <h2>⚔️ Bienvenido a Estiria</h2>
                                                                                                                                                                                                                                                                                                                <p>${currentUser?.nombre || currentUser?.telefono || 'Ciudadano'}</p>
                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                        <div class="card">
                                                                                                                                                                                                                                                                                                                              <h3>📢 Anuncios</h3>
                                                                                                                                                                                                                                                                                                                                    <p>Próximamente...</p>
                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                            <div class="card">
                                                                                                                                                                                                                                                                                                                                                  <h3>📅 Eventos</h3>
                                                                                                                                                                                                                                                                                                                                                        <p>Próximamente...</p>
                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                ${currentUser?.rol === 'admin' ? `
                                                                                                                                                                                                                                                                                                                                                                    <div class="card" style="border-color: var(--accent)">
                                                                                                                                                                                                                                                                                                                                                                          <h3>🛡️ Panel Admin</h3>
                                                                                                                                                                                                                                                                                                                                                                                <p>Tienes acceso de administrador.</p>
                                                                                                                                                                                                                                                                                                                                                                                    </div>` : ''}
                                                                                                                                                                                                                                                                                                                                                                                      `;
                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                      function renderBanco() {
                                                                                                                                                                                                                                                                                                                                                                                        mainContent.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                            <div class="card">
                                                                                                                                                                                                                                                                                                                                                                                                  <h3>🏦 Banco de Estiria</h3>
                                                                                                                                                                                                                                                                                                                                                                                                        <p>Próximamente...</p>
                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                              `;
                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                              function renderBiblioteca() {
                                                                                                                                                                                                                                                                                                                                                                                                                mainContent.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="card">
                                                                                                                                                                                                                                                                                                                                                                                                                          <h3>📚 Biblioteca</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                <p>Próximamente...</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                      `;
                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                      function renderPerfil() {
                                                                                                                                                                                                                                                                                                                                                                                                                                        mainContent.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3>👤 Mi Perfil</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>Teléfono: ${currentUser?.telefono || ''}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>Rol: ${currentUser?.rol || 'jugador'}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button class="btn btn-secondary btn-full" id="logout-btn">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Cerrar sesión
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.getElementById('logout-btn').addEventListener('click', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        auth.signOut();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // ===== ERRORES =====
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          function showError(msg) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            loginError.textContent = msg;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              loginError.classList.remove('hidden');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              function hideError() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                loginError.classList.add('hidden');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }importimport